[package]
name = "issue-board"
version = "0.1.0"
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.druid]
git = "https://github.com/xi-editor/druid"

[patch."https://github.com/xi-editor/druid".druid]
path = "../druid/druid"
